GET http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

###

POST http://localhost:3000/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2019-08-05",
  "type": "OccupationalHealthcare",
  "specialist": "MD House",
  "employerName": "HyPD",
  "diagnosisCodes": ["Z57.1", "Z74.3", "M51.2"],
  "description":
    "Patient was found stuck in a glue trap.",
  "sickLeave": {
    "startDate": "2019-08-05",
    "endDate": "2019-08-28"
  }
}

###

GET http://localhost:3000/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667

###

POST http://localhost:3000/api/patients/d2773c6e-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2019-09-10",
  "specialist": "MD House",
  "type": "OccupationalHealthcare",
  "employerName": "Classified",
  "description": "Prescriptions renewed."
}