GET http://localhost:3003/hello

###

POST http://localhost:3003/exercises 
Content-Type: application/json

{
  "daily_exercises": [2,2,2,5,4,2], "target": 2
}

###

POST http://localhost:3003/exercises 
Content-Type: application/json

{
  "daily_exercises": [], "target": 2
}